import mapMessages from './mapMessages.js';
// English is the key; all visitor copy is translated here, including alerts.
export const hi = {
  'What would help?':'किस तरह की मदद चाहिए?',
  'Choose one or more options.':'एक या अधिक विकल्प चुनें।',
  'What would make your journey easier?':'आपकी यात्रा को आसान बनाने में क्या मदद करेगा?',
  ...mapMessages,
  'Navigate public spaces with confidence.':'सार्वजनिक स्थानों पर आत्मविश्वास से चलें।',
  'Accessible guidance, real-time updates and assistance when you need it.':'सुलभ मार्गदर्शन, तुरंत जानकारी और ज़रूरत पर सहायता।',
  'Start your journey':'अपनी यात्रा शुरू करें','Start Journey':'यात्रा शुरू करें','Continue':'आगे बढ़ें','Back':'वापस','Home':'मुख्य पृष्ठ',
  'Sanket Saarthi home':'संकेत सारथी का मुख्य पृष्ठ','Skip to content':'मुख्य सामग्री पर जाएँ','Main navigation':'मुख्य नेविगेशन','Staff Login':'कर्मचारी लॉगिन',
  'Voice Assist':'आवाज़ से मार्गदर्शन','ON':'चालू','OFF':'बंद','Language':'भाषा','Switch to dark mode':'डार्क मोड चालू करें','Switch to light mode':'लाइट मोड चालू करें',
  'Read Instruction':'निर्देश सुनें','Stop Voice':'आवाज़ रोकें','Speech is unavailable in this browser.':'इस ब्राउज़र में आवाज़ उपलब्ध नहीं है।',
  'Station and accessibility':'स्टेशन और सुलभता','Search station or city':'स्टेशन या शहर खोजें','Station name, city or code':'स्टेशन का नाम, शहर या कोड',
  'Station suggestions':'स्टेशन के सुझाव','No stations found.':'कोई स्टेशन नहीं मिला।','{count} stations found.':'{count} स्टेशन मिले।',
  'Selected station':'चुना गया स्टेशन','Change station':'स्टेशन बदलें','Station identified from QR':'क्यूआर से स्टेशन की पहचान हुई','Current location':'वर्तमान स्थान',
  'Guidance is configured for Bhopal Junction only.':'मार्गदर्शन अभी केवल भोपाल जंक्शन के लिए उपलब्ध है।','Use Bhopal Junction':'भोपाल जंक्शन चुनें',
  'Choose your accessibility needs':'अपनी सुलभता संबंधी ज़रूरतें चुनें','Select what would make your journey easier. You can choose more than one.':'जो आपकी यात्रा आसान बनाए, उसे चुनें। आप एक से अधिक विकल्प चुन सकते हैं।',
  'Mobility':'चलने-फिरने में सहायता','Blind or Low Vision':'दृष्टिहीन या कम दृष्टि','Deaf or Hard of Hearing':'बधिर या सुनने में कठिनाई','Cognitive / Learning Support':'समझने या सीखने में सहायता','Speech / Communication Support':'बोलने या संवाद में सहायता','Other / Custom Support':'अन्य / अपनी ज़रूरत के अनुसार',
  'What would help you during your journey?':'यात्रा में आपको किस तरह की मदद चाहिए?','Accessible Route Only':'केवल सुलभ मार्ग','Wheelchair Assistance':'व्हीलचेयर सहायता','Human Assistance':'कर्मचारी की सहायता','Wheelchair + Human Assistance':'व्हीलचेयर और कर्मचारी की सहायता',
  'Step-Free Navigation':'सीढ़ियों के बिना मार्ग','Visual Alerts':'दृश्य सूचनाएँ','Vibration Alerts':'कंपन सूचनाएँ','Simple Guidance':'सरल मार्गदर्शन',
  'Voice guidance enabled. You can turn it off above.':'आवाज़ से मार्गदर्शन चालू है। आप इसे ऊपर से बंद कर सकते हैं।',
  'Visual and vibration alerts enabled.':'दृश्य और कंपन सूचनाएँ चालू हैं।','Short instructions enabled.':'छोटे निर्देश चालू हैं।','You can request help without speaking.':'आप बोले बिना मदद माँग सकते हैं।',
  'What do you need help with?':'आपको किस काम में मदद चाहिए?','Catch a Train':'ट्रेन पकड़ना','Exit the Station':'स्टेशन से बाहर जाना','Find a Facility':'सुविधा खोजना','Request Assistance':'सहायता माँगें',
  'Train number':'ट्रेन नंबर','Find train':'ट्रेन खोजें','Finding train…':'ट्रेन खोजी जा रही है…','Enter a five-digit train number.':'पाँच अंकों का ट्रेन नंबर डालें।','Train not available. Try sample train 12345.':'ट्रेन उपलब्ध नहीं है। नमूना ट्रेन 12345 आज़माएँ।',
  'Your journey':'आपकी यात्रा','Starting from':'शुरुआती स्थान','Destination':'गंतव्य','Selected support':'चुनी गई सहायता','Standard text guidance':'सामान्य लिखित मार्गदर्शन',
  'Train {number}':'ट्रेन {number}','Platform {number}':'प्लेटफ़ॉर्म {number}','On Time':'समय पर','ON_TIME':'समय पर','Delayed':'देरी से','DELAYED':'देरी से','Cancelled':'रद्द','CANCELLED':'रद्द',
  'Sample train data. Platform updates are controlled by staff.':'ट्रेन की जानकारी नमूना है। प्लेटफ़ॉर्म की जानकारी कर्मचारी बदलते हैं।','Train details from the connected provider.':'ट्रेन की जानकारी जुड़े हुए सेवा प्रदाता से है।',
  'This train has no configured indoor route here.':'इस ट्रेन के लिए यहाँ अंदर का मार्ग उपलब्ध नहीं है।','Waiting for station information…':'स्टेशन की जानकारी का इंतज़ार है…','Station updates are unavailable. Check with staff.':'स्टेशन की ताज़ा जानकारी उपलब्ध नहीं है। कर्मचारी से पूछें।',
  'Choose a facility':'सुविधा चुनें','Sample route and distances; follow station signs.':'मार्ग और दूरी नमूना हैं; स्टेशन के संकेतों का पालन करें।',
  'Where would you like to receive the wheelchair?':'आपको व्हीलचेयर कहाँ चाहिए?','Where should staff meet you?':'कर्मचारी आपसे कहाँ मिलें?','Meeting point':'मिलने का स्थान',
  'What would you like help with?':'आपको किस काम में सहायता चाहिए?','Reaching my platform':'अपने प्लेटफ़ॉर्म तक पहुँचना','Navigating the station':'स्टेशन में रास्ता खोजना','Boarding assistance':'ट्रेन में चढ़ने में सहायता','Communication assistance':'संवाद में सहायता','Other':'अन्य',
  'Request Wheelchair':'व्हीलचेयर माँगें','Request assistance and start':'सहायता माँगें और शुरू करें','Start without requesting help':'अभी सहायता माँगे बिना शुरू करें',
  'This coordinates assistance with demo staff, not an official railway reservation.':'यह डेमो कर्मचारियों से सहायता का समन्वय है, आधिकारिक रेलवे आरक्षण नहीं।',
  'Wheelchair required':'व्हीलचेयर चाहिए','Human assistance required':'कर्मचारी की सहायता चाहिए','Sending…':'भेजा जा रहा है…','Request not sent. Check your connection and try again.':'अनुरोध नहीं भेजा गया। इंटरनेट जाँचकर फिर कोशिश करें।',
  'How can we help?':'हम कैसे मदद करें?','Assistance type':'सहायता का प्रकार','Mobility Assistance':'चलने-फिरने में सहायता','Navigation Help':'रास्ता खोजने में मदद','Communication Assistance':'संवाद में सहायता','Boarding Assistance':'ट्रेन में चढ़ने में सहायता','Luggage Assistance':'सामान में सहायता','Cancel':'रद्द करें',
  'Request received':'अनुरोध मिल गया','Finding available staff…':'उपलब्ध कर्मचारी खोजे जा रहे हैं…','Assistance confirmed':'सहायता की पुष्टि हो गई','Wheelchair assistance confirmed':'व्हीलचेयर सहायता की पुष्टि हो गई','Your wheelchair assistance request has been accepted.':'आपकी व्हीलचेयर सहायता का अनुरोध स्वीकार कर लिया गया है।','A staff member has accepted your assistance request.':'एक कर्मचारी ने आपकी सहायता का अनुरोध स्वीकार कर लिया है।','Wheelchair and human assistance have been accepted for your journey.':'आपकी यात्रा के लिए व्हीलचेयर और कर्मचारी की सहायता स्वीकार कर ली गई है।',
  'Assistance is on the way':'सहायता आपके पास आ रही है','Staff are on the way to your meeting point.':'कर्मचारी आपके मिलने के स्थान की ओर आ रहे हैं।','Assistance completed':'सहायता पूरी हो गई','Your assistance request is complete.':'आपका सहायता अनुरोध पूरा हो गया है।','Assistance request active':'सहायता का अनुरोध जारी है','Assistance updates are unavailable.':'सहायता की ताज़ा जानकारी उपलब्ध नहीं है।','View assistance':'सहायता देखें',
  'Next action':'अगला कदम','Journey progress':'यात्रा की प्रगति','Route status':'मार्ग की स्थिति','Near your route':'आपके मार्ग के पास','Completed':'पूरा हुआ','You are here':'आप यहाँ हैं','Up next':'अगला पड़ाव','Last confirmed checkpoint':'अंतिम पुष्टि किया गया स्थान',
  'Connected to station':'स्टेशन से जुड़ा है','Updates not confirmed':'ताज़ा जानकारी की पुष्टि नहीं हुई','Availability not confirmed':'उपलब्धता की पुष्टि नहीं हुई','Step-free throughout':'पूरे मार्ग में सीढ़ियों की ज़रूरत नहीं','Predefined station route':'पहले से निर्धारित स्टेशन मार्ग',
  'Pause here. An accessible route is not confirmed. Request staff assistance.':'यहीं रुकें। सुलभ मार्ग की पुष्टि नहीं हुई है। कर्मचारी की सहायता माँगें।',
  'Your route changed. Confirm a checkpoint on the updated route or request staff assistance.':'आपका मार्ग बदल गया है। नए मार्ग पर अपना स्थान पुष्टि करें या कर्मचारी की सहायता माँगें।',
  'Continue straight for 70 m towards Ramp B.':'रैंप B की ओर 70 मीटर सीधे जाएँ।','Go to {place}.':'{place} पर जाएँ।','Follow the signs.':'संकेतों का पालन करें।','Confirm when you arrive.':'पहुँचने पर पुष्टि करें।','Follow the marked accessible route towards {place}.':'चिह्नित सुलभ मार्ग से {place} की ओर जाएँ।',
  'You’ve arrived.':'आप पहुँच गए हैं।','Journey completed.':'यात्रा पूरी हुई।','Please check the station display before boarding.':'ट्रेन में चढ़ने से पहले स्टेशन का सूचना बोर्ड देखें।','Was this route accessible?':'क्या यह मार्ग सुलभ था?','Yes':'हाँ','Report an Issue':'समस्या बताएँ','Thank you. Your feedback is noted for this session.':'धन्यवाद। इस सत्र के लिए आपकी प्रतिक्रिया दर्ज है।','Please report the issue to the Assistance Desk or request help below.':'सहायता केंद्र को समस्या बताएँ या नीचे मदद माँगें।','Need help boarding?':'ट्रेन में चढ़ने में मदद चाहिए?','Request Boarding Assistance':'ट्रेन में चढ़ने के लिए सहायता माँगें',
  'I’ve reached {place}':'मैं {place} पहुँच गया/गई हूँ','Simulate QR Scan':'क्यूआर स्कैन का परीक्षण करें','Checkpoint':'चेकपॉइंट','Choose checkpoint':'चेकपॉइंट चुनें','Open checkpoint URL':'चेकपॉइंट लिंक खोलें','Choose the checkpoint you have reached.':'जहाँ पहुँच गए हैं, वह चेकपॉइंट चुनें।','This checkpoint is not on the current route.':'यह चेकपॉइंट वर्तमान मार्ग पर नहीं है।',
  'Platform change':'प्लेटफ़ॉर्म बदला','Your journey has been updated.':'आपकी यात्रा अपडेट हो गई है।','Route update':'मार्ग बदला','Facility update':'सुविधा की जानकारी','Old route':'पुराना मार्ग','New route':'नया मार्ग','Continue with new route':'नए मार्ग पर आगे बढ़ें','View updated route':'नया मार्ग देखें',
  '{facility}: {before} → {after}.':'{facility}: {before} → {after}।','Operational':'चालू','Unavailable':'उपलब्ध नहीं','Maintenance':'रखरखाव जारी','Not confirmed':'पुष्टि नहीं हुई',
  'Entrance Gate 1':'प्रवेश द्वार 1','Ramp B':'रैंप B','Lift A':'लिफ्ट A','Lift B':'लिफ्ट B','Accessible Corridor':'सुलभ गलियारा','Corridor C':'गलियारा C','Accessible Washroom':'सुलभ शौचालय','Assistance Desk':'सहायता केंद्र','Accessible Exit':'सुलभ निकास','Gate 2':'द्वार 2','Accessible Entrance':'सुलभ प्रवेश',
  'Main concourse':'मुख्य परिसर','70 m from Entrance Gate 1':'प्रवेश द्वार 1 से 70 मीटर','40 m from Ramp B':'रैंप B से 40 मीटर','Sample distances and locations':'नमूना दूरी और स्थान',
  'Example journeys':'यात्रा के उदाहरण','Journey preview':'यात्रा की झलक','Step-free route':'सीढ़ियों के बिना मार्ग','Bhopal Junction':'भोपाल जंक्शन','Railway station':'रेलवे स्टेशन','Airport':'हवाई अड्डा','Hospital':'अस्पताल','Coming soon':'जल्द उपलब्ध','Entrance':'प्रवेश','Reception':'स्वागत कक्ष','Department':'विभाग','Departure gate':'प्रस्थान द्वार','Your starting point':'आपकी शुरुआत','Step-free access':'सीढ़ियों के बिना पहुँच','Accessible lift':'सुलभ लिफ्ट','Your destination':'आपका गंतव्य','Predefined route':'निर्धारित मार्ग','Station updates':'स्टेशन की जानकारी','Pause':'रोकें','Play':'चलाएँ','Preview {place}':'{place} की झलक',
  'Railway Stations':'रेलवे स्टेशन','Hospitals':'अस्पताल','Airports':'हवाई अड्डे','Government Offices':'सरकारी कार्यालय','Find your route':'अपना मार्ग खोजें',
  'Ask Saarthi':'सारथी से पूछें','Your Saarthi':'आपका सारथी','Close assistant':'सहायक बंद करें','Website & voice guide':'वेबसाइट और आवाज़ से मार्गदर्शन','Message Saarthi':'सारथी को संदेश','Ask your Saarthi…':'अपने सारथी से पूछें…','Send message':'संदेश भेजें','Start journey':'यात्रा शुरू करें','Mobility support':'चलने-फिरने में सहायता','Help':'मदद','Voice':'आवाज़','Stop':'रोकें','Start voice input':'आवाज़ से बोलना शुरू करें','Stop listening':'सुनना बंद करें','Listening…':'सुन रहा हूँ…','Voice received.':'आवाज़ प्राप्त हुई।','Press Voice to enable your microphone.':'माइक्रोफ़ोन चालू करने के लिए आवाज़ दबाएँ।','Voice input unavailable here. Type below.':'यहाँ आवाज़ से लिखना उपलब्ध नहीं है। नीचे लिखें।','Microphone access denied. Type your message below.':'माइक्रोफ़ोन की अनुमति नहीं मिली। नीचे संदेश लिखें।','Could not hear you. Try again or type below.':'सुन नहीं पाया। फिर कोशिश करें या नीचे लिखें।',
  'I can help you choose a station, set up support, or request assistance.':'मैं स्टेशन चुनने, सहायता चुनने या मदद माँगने में आपका मार्गदर्शन कर सकता हूँ।','Choose a station and your accessibility needs on the same screen.':'एक ही स्क्रीन पर स्टेशन और अपनी सुलभता संबंधी ज़रूरतें चुनें।','Choose Mobility, then select a route, wheelchair, staff help, or both.':'चलने-फिरने में सहायता चुनें, फिर मार्ग, व्हीलचेयर, कर्मचारी या दोनों चुनें।','Use Request Assistance during your journey. You can choose help without speaking.':'यात्रा के दौरान सहायता माँगें बटन का उपयोग करें। आप बोले बिना मदद चुन सकते हैं।','Dark mode is on.':'डार्क मोड चालू है।','Light mode is on.':'लाइट मोड चालू है।','You’re on the home page.':'आप मुख्य पृष्ठ पर हैं।','Try Start journey, Mobility support, or Help.':'यात्रा शुरू करें, चलने-फिरने में सहायता या मदद चुनें।','More venue types are coming soon.':'अन्य स्थानों के लिए मार्गदर्शन जल्द उपलब्ध होगा।',
};
export function translate(language, key, values = {}) {
  const text = language === 'hi' ? (hi[key] ?? key) : key;
  return text.replace(/\{(\w+)\}/g, (_, name) => String(values[name] ?? `{${name}}`));
}
export function placeName(language, name = '') {
  const match = /^Platform (.+)$/.exec(name);
  return match ? translate(language,'Platform {number}',{number:match[1]}) : translate(language,name);
}
