import { useEffect,useEffectEvent,useState,useSyncExternalStore } from 'react';
import StatusIcon from '../components/StatusIcon';
import AssistancePanel from '../components/AssistancePanel';
import { FACILITIES,checkpointUrl,statusLabel } from '../data/journey';
import { getStationByCode as stationByCode } from '../services/stationService';
import StationMap from '../components/StationMap';
import { processCheckpoint } from '../services/checkpointService';
import { journeyRoute,checkpointName,instructionText,alertText } from '../data/guidance';
import { speak,stopSpeech,isSpeaking,subscribeSpeech } from '../services/speechService';
import { useI18n } from '../i18n/context';
export default function Dashboard({journey,setJourney,live}){
  const {t,place,language}=useI18n();
  const [mapOpen,setMapOpen]=useState(false);
  const [scan,setScan]=useState(''),[feedback,setFeedback]=useState(''),[scanError,setScanError]=useState(false);
  const {preferences,checkpoint}=journey;
  const platform=live.train?.platform;
  const route=journeyRoute(journey,platform,live.facilities);
  const destination=route.steps.at(-1),index=route.steps.findIndex(s=>s.id===checkpoint);
  const arrived=checkpoint===destination.id && !destination.id.endsWith('—');
  const connected=!live.loading&&!live.error&&!live.fromCache;
  const instruction=instructionText(route,checkpoint,preferences.simpleGuidance,connected,t,place);
  const station=stationByCode(journey.stationCode);
  const speaking=useSyncExternalStore(subscribeSpeech,isSpeaking,()=>false);
  const readAutomatically=useEffectEvent(()=>{if(preferences.audioGuidance&&connected)speak(instruction,undefined,language);});
  // Operational alerts own platform/facility speech. Only checkpoint, language or
  // voice changes trigger this instruction, so a reroute alert is not interrupted.
  useEffect(()=>{readAutomatically();return()=>stopSpeech();},[checkpoint,language,preferences.audioGuidance,connected]);
  function confirmCheckpoint(id){if(!route.steps.some(s=>s.id===id)){setScanError(true);return;}stopSpeech();setScanError(false);setJourney(j=>processCheckpoint(checkpointUrl(id).split('?')[1],j)||j);history.replaceState({screen:'journey'},'',checkpointUrl(id));}
  return <main className="live-page"><div className="journey-title"><div><div className="eyebrow">{language==='hi'?station?.nameHi:station?.name}</div><h1>{arrived?t('You’ve arrived.'):place(destination.name)}</h1>{journey.purpose==='train'&&<p>{language==='hi'?(journey.train?.nameHi||journey.train?.name):journey.train?.name} · {t(live.train?.status||'Not confirmed')}</p>}</div><span className="connection-state">{connected?'● ':'○ '}{t(connected?'Connected to station':'Updates not confirmed')}</span></div>
    <div className={preferences.visualAlerts?'alerts prominent':'alerts'}>{live.alerts.map(event=>{const alert=alertText(event,t,place);return <section key={event.id} role="alert" data-tone={event.kind==='platform'?'warning':event.after!=='Operational'?'error':'info'}><strong className="status-heading"><StatusIcon kind={event.kind==='platform'?'warning':event.after!=='Operational'?'error':'info'}/>{alert.title}</strong><p>{alert.text}</p>{alert.oldRoute&&<p>{t('Old route')}: {alert.oldRoute}</p>}{alert.newRoute&&<p>{t('New route')}: {alert.newRoute}</p>}{alert.blocked&&<p>{t('Pause here. An accessible route is not confirmed. Request staff assistance.')}</p>}<button onClick={()=>{document.getElementById('journey-timeline')?.focus();live.dismissAlert(event.id);}}>{t(event.kind==='facility'?'Continue with new route':'View updated route')}</button></section>;})}</div>
    {!connected&&<p role="alert" className="notice">{t('Station updates are unavailable. Check with staff.')}</p>}
    <div className="live-columns"><div><section className="next-action" aria-labelledby="next-heading"><div className="eyebrow">{t('Next action')}</div><h2 id="next-heading" className={preferences.simpleGuidance?'simple-instruction':''}>{arrived?place(destination.name):instruction}</h2><p>{arrived?t('Journey completed.'):<>{t('Current location')}: <strong>{place(checkpointName(checkpoint))}</strong><small> · {t('Last confirmed checkpoint')}</small></>}</p><button className="secondary-action" disabled={!window.speechSynthesis} onClick={()=>speaking?stopSpeech():speak(instruction,undefined,language)}>{t(speaking?'Stop Voice':'Read Instruction')}</button></section>
    {arrived?<section className="arrival-feedback">{journey.purpose==='train'&&<p>{t('Please check the station display before boarding.')}</p>}<h3>{t('Was this route accessible?')}</h3><div className="action-row"><button className="secondary-action" onClick={()=>setFeedback('Thank you. Your feedback is noted for this session.')}>{t('Yes')}</button><button className="secondary-action" onClick={()=>setFeedback('Please report the issue to the Assistance Desk or request help below.')}>{t('Report an Issue')}</button></div><p role="status">{t(feedback)}</p>{journey.purpose==='train'&&<h3>{t('Need help boarding?')}</h3>}</section>:<><section id="journey-timeline" tabIndex={-1} className="timeline-section"><h3>{t('Journey progress')}</h3>{index<0&&<p role="alert">{t('Your route changed. Confirm a checkpoint on the updated route or request staff assistance.')}</p>}<ol className="journey-timeline">{route.steps.map((step,i)=><li key={step.id} className={i===index?'current':i<index?'complete':''} aria-current={i===index?'step':undefined}><span aria-hidden="true">{i<index?'✓':i===index?'●':'○'}</span><div><strong>{place(step.name)}</strong><small>{t(i<index?'Completed':i===index?'You are here':'Up next')}</small></div></li>)}</ol></section><div className="checkpoint-controls"><button className="continue-button" disabled={route.blocked||index<0||!connected} onClick={()=>confirmCheckpoint(route.steps[index+1]?.id)}>{t('I’ve reached {place}',{place:place(route.steps[index+1]?.name||'Checkpoint')})} →</button><details><summary>{t('Simulate QR Scan')}</summary><p>{t('Choose the checkpoint you have reached.')}</p><label>{t('Checkpoint')}<select value={scan} onChange={e=>setScan(e.target.value)}><option value="">{t('Choose checkpoint')}</option>{route.steps.map(s=><option key={s.id} value={s.id}>{place(s.name)}</option>)}</select></label><button className="secondary-action" disabled={!scan||!connected||route.blocked} onClick={()=>confirmCheckpoint(scan)}>{t('Simulate QR Scan')}</button>{scan&&<a href={checkpointUrl(scan)}>{t('Open checkpoint URL')}</a>}</details>{scanError&&<p role="alert">{t('This checkpoint is not on the current route.')}</p>}</div></>}
    <AssistancePanel checkpoint={checkpoint} destination={destination} journey={journey} setJourney={setJourney} boarding={arrived&&journey.purpose==='train'}/><details className="map-disclosure" onToggle={event=>setMapOpen(event.currentTarget.open)}><summary>{t('View Station Map')}</summary>{mapOpen&&<StationMap station={station}/>}</details>
    </div><aside className="route-sidebar"><section className="route-health" data-tone={!connected?'info':route.blocked?'warning':'success'}><h3 className="status-heading"><StatusIcon kind={!connected?'info':route.blocked?'warning':'success'}/>{t('Route status')}</h3><p>{!connected?t('Availability not confirmed'):route.blocked?t('Pause here. An accessible route is not confirmed. Request staff assistance.'):t(preferences.stepFreeNavigation?'Step-free throughout':'Predefined station route')}</p>{route.lift&&<p>{place(route.lift)}: {t(statusLabel(live.facilities.find(f=>f.name===route.lift||f.id===(route.lift==='Lift A'?'lift-a':'lift-b'))?.status))}</p>}<small>{t('Sample route and distances; follow station signs.')}</small></section><section><h3>{t('Near your route')}</h3>{FACILITIES.map(f=><div className="nearby-row" key={f.id}><strong>{place(f.name)}</strong><small>{t(f.nearby)}</small><span>{t(statusLabel(live.facilities.find(item=>item.id===f.id)?.status))}</span></div>)}<div className="nearby-row"><strong>{t('Accessible Exit')}</strong><small>{t('Gate 2')}</small></div></section></aside></div>
  </main>;
}
